"""Add target and unit for daily quest

Revision ID: 3f76772abd3f
Revises: 329de1e8b4ea
Create Date: 2024-11-25 17:59:35.847527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f76772abd3f'
down_revision = '329de1e8b4ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_quest_template', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('unit', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_quest_template', schema=None) as batch_op:
        batch_op.drop_column('unit')
        batch_op.drop_column('target')

    # ### end Alembic commands ###
