"""Add target and unit for daily quest

Revision ID: db9d3cfd68af
Revises: 3f76772abd3f
Create Date: 2024-11-25 18:15:25.203875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db9d3cfd68af'
down_revision = '3f76772abd3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quest', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('unit', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quest', schema=None) as batch_op:
        batch_op.drop_column('unit')
        batch_op.drop_column('target')

    # ### end Alembic commands ###
